# Generated by Django 5.1.1 on 2024-10-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exoplanets", "0003_alter_user_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
